---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: testcontainers/helloworld
        ports:
        - containerPort: 8080   # Use port 3000



# apiVersion: v1
# kind: Service
# metadata:
#   name: tetris
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 8080
#       nodePort: 30000  # Specify the desired NodePort number
#   selector:
#     app: tetris
apiVersion: v1
kind: Service
metadata:
  name: tetris
  labels:
    app: tetris
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    targetPort: 8080
    protocol: TCP
  selector:
    app: tetris