pipeline{
    agent any
    environment {
        SONAR_TOKEN = credentials('sonarqube-jenkins')
    }

    tools{
        jdk 'jdk17'
        terraform 'terraform'
    }
    stages{
        stage('clean Workspace'){
            steps{
                cleanWs()
            }
        }
        stage('checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/techinanutshellhack/devsecops.git'
            }
        }
        stage('Terraform version'){
             steps{
                 sh 'terraform --version'
                }
        }
        stage("Sonarqube Analysis "){
            steps{
                // withSonarQubeEnv('sonar-server') {
                //     sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Terraform \
                //     -Dsonar.projectKey=Terraform '''
                    // Execute SonarCloud analysis
                  withSonarQubeEnv('SonarCloud') {
                    sh 'npm install -g sonarqube-scanner'
                    sh 'sonar-scanner \
                        -Dsonar.projectKey=techinanutshell_tetris-devsecops \
                        -Dsonar.organization=techinanutshellhack \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.login=${SONAR_TOKEN}'
                }
            }
        }
        stage("quality gate"){
           steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonarqube-jenkins' 
                }
            } 
        }
        stage('TRIVY FS SCAN') {
            steps {
                sh "trivy fs . > trivyfs.txt"
            }
        }
        stage('Excutable permission to userdata'){
            steps{
                sh 'chmod 777 website.sh'
            }
        }
        stage('Terraform init'){
            steps{
                sh 'terraform init'
            }
        }
        stage('Terraform plan'){
            steps{
                sh 'terraform plan'
            }
        }
        stage('Terraform apply'){
            steps{
                sh 'terraform ${action} --auto approve'
            }
        }
    }
}